<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="WAL.fs" />
    <Compile Include="SkipList.fs" />
    <Compile Include="MemTable.fs" />
    <Compile Include="BloomFilter.fs" />
    <Compile Include="SSTable.fs" />
    <Compile Include="LsmTransaction.fs" />
    <Compile Include="LsmTree.fs" />
  </ItemGroup>

</Project>
